@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

package chancecards {
    abstract ChanceCard {
        -cardName : String

        {abstract} +doCardAction(playerID:UUID) : void
    }

    abstract MoveToFieldCC {
    }

    abstract MoveToColorCC {
    }

    ChanceCard <|-- MoveToFieldCC
    ChanceCard <|-- MoveToColorCC

    class BrownRedCC {
    }

    class LightBlueCC {
    }

    class LightBlueYellowCC {
    }

    class OrangeBlueCC {
    }

    class OrangeCC {
    }

    class RedCC {
    }

    class SalmonGreenCC {
    }

    MoveToColorCC <|-- BrownRedCC
    MoveToColorCC <|-- LightBlueCC
    MoveToColorCC <|-- LightBlueYellowCC
    MoveToColorCC <|-- OrangeBlueCC
    MoveToColorCC <|-- OrangeCC
    MoveToColorCC <|-- RedCC
    MoveToColorCC <|-- SalmonGreenCC

    class BoardWalkCC {
    }

    class SkateparkCC {
    }

    class StartCC {
    }

    MoveToFieldCC <|-- BoardWalkCC
    MoveToFieldCC <|-- SkateparkCC
    MoveToFieldCC <|-- StartCC

    class BailCC {
    }

    class BirthdayCC {
    }

    class CarCC {
    }

    class DidHomeWorkCC {
    }

    class EatCandyCC {
    }

    class MoveFieldsCC {
    }

    class MoveOrDrawCC {
    }

    class ShipCC {
    }

    ChanceCard <|-- BailCC
    ChanceCard <|-- BirthdayCC
    ChanceCard <|-- CarCC
    ChanceCard <|-- DidHomeWorkCC
    ChanceCard <|-- EatCandyCC
    ChanceCard <|-- MoveFieldsCC
    ChanceCard <|-- MoveOrDrawCC
    ChanceCard <|-- ShipCC
}

@enduml